# Generated by Django 5.1.7 on 2025-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='log_images/'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
