# Generated by Django 5.1.7 on 2025-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
